//*****************************************************************************
// Copyright (c) 2014 Texas Instruments Incorporated.  All rights reserved.
// Software License Agreement
// 
//   Redistribution and use in source and binary forms, with or without
//   modification, are permitted provided that the following conditions
//   are met:
// 
//   Redistributions of source code must retain the above copyright
//   notice, this list of conditions and the following disclaimer.
// 
//   Redistributions in binary form must reproduce the above copyright
//   notice, this list of conditions and the following disclaimer in the
//   documentation and/or other materials provided with the  
//   distribution.
// 
//   Neither the name of Texas Instruments Incorporated nor the names of
//   its contributors may be used to endorse or promote products derived
//   from this software without specific prior written permission.
// 
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
// "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
// LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
// A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
// OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
// SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
// LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
// OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//
// This file was automatically generated by the Tiva C Series PinMux Utility
// Version: 1.0.4
//
//*****************************************************************************

#include <stdint.h>
#include <stdbool.h>
#include "L5.h"
#include "inc/hw_types.h"
#include "inc/hw_memmap.h"
#include "inc/hw_gpio.h"
#include "driverlib/sysctl.h"
#include "driverlib/pin_map.h"
#include "driverlib/gpio.h"

#define user_button1      GPIO_PIN_0
#define user_button2      GPIO_PIN_4
#define red_LED           GPIO_PIN_1
#define blue_LED          GPIO_PIN_2
#define green_LED					GPIO_PIN_3

//*****************************************************************************
void
PortFunctionInit(void)
{
    //
    // Enable Peripheral Clocks 
    //
    SysCtlPeripheralEnable(SYSCTL_PERIPH_GPIOF);

    //
    // Enable pin PF0 for GPIOInput
    //

    //
    //First open the lock and select the bits we want to modify in the GPIO commit register.
    //
    HWREG(GPIO_PORTF_BASE + GPIO_O_LOCK) = GPIO_LOCK_KEY;
    HWREG(GPIO_PORTF_BASE + GPIO_O_CR) = 0x1;

    //
    //Now modify the configuration of the pins that we unlocked.
    //
    GPIOPinTypeGPIOInput(GPIO_PORTF_BASE, GPIO_PIN_0);

    //
    // Enable pin PF3 for GPIOOutput
    //
    GPIOPinTypeGPIOOutput(GPIO_PORTF_BASE, GPIO_PIN_3);

    //
    // Enable pin PF4 for GPIOInput
    //
    GPIOPinTypeGPIOInput(GPIO_PORTF_BASE, GPIO_PIN_4);

    //
    // Enable pin PF1 for GPIOOutput
    //
    GPIOPinTypeGPIOOutput(GPIO_PORTF_BASE, GPIO_PIN_1);

    //
    // Enable pin PF2 for GPIOOutput
    //
    GPIOPinTypeGPIOOutput(GPIO_PORTF_BASE, GPIO_PIN_2);
}

// void setup_GPIOs();
int main(void)
{
	
		 //initialize the GPIO ports	
		 PortFunctionInit();
	
     signed char s = 0;
     // setup_GPIOs();
     while(1)
     {
          if(GPIOPinRead(GPIO_PORTF_BASE, GPIO_PIN_4)==0x00) //SW1 is pressed
          {
              while(GPIOPinRead(GPIO_PORTF_BASE, GPIO_PIN_4)==0x00); //SW1 is pressed
              s++;
          }
          if(s > 7)
          {
              s = 0;
          }
          if(GPIOPinRead(GPIO_PORTF_BASE, GPIO_PIN_0)==0x00) //SW2 is pressed
          {
              while(GPIOPinRead(GPIO_PORTF_BASE, GPIO_PIN_0)==0x00); //SW2 is pressed
              s--;
          }
          if(s < 0)
          {
              s = 7;
          }
          switch(s)
          {
              case 1:
              {
                  GPIOPinWrite(GPIO_PORTF_BASE, GPIO_PIN_1, 0x02);
                  GPIOPinWrite(GPIO_PORTF_BASE, GPIO_PIN_3, 0x00);
                  GPIOPinWrite(GPIO_PORTF_BASE, GPIO_PIN_2, 0x00);
                  break;
              }
              case 2:
              {
                  GPIOPinWrite(GPIO_PORTF_BASE, GPIO_PIN_1, 0x00);
                  GPIOPinWrite(GPIO_PORTF_BASE, GPIO_PIN_3, 0x08);
                  GPIOPinWrite(GPIO_PORTF_BASE, GPIO_PIN_2, 0x00);
                  break;
              }
              case 3:
              {
                  GPIOPinWrite(GPIO_PORTF_BASE, GPIO_PIN_1, 0x00);
                  GPIOPinWrite(GPIO_PORTF_BASE, GPIO_PIN_3, 0x00);
                  GPIOPinWrite(GPIO_PORTF_BASE, GPIO_PIN_2, 0x04);
                  break;
              }
              case 4:
              {
                  GPIOPinWrite(GPIO_PORTF_BASE, GPIO_PIN_1, 0x02);
                  GPIOPinWrite(GPIO_PORTF_BASE, GPIO_PIN_3, 0x08);
                  GPIOPinWrite(GPIO_PORTF_BASE, GPIO_PIN_2, 0x00);
                  break;
              }
              case 5:
              {
                  GPIOPinWrite(GPIO_PORTF_BASE, GPIO_PIN_1, 0x02);
                  GPIOPinWrite(GPIO_PORTF_BASE, GPIO_PIN_3, 0x00);
                  GPIOPinWrite(GPIO_PORTF_BASE, GPIO_PIN_2, 0x04);
                  break;
              }
              case 6:
              {
                  GPIOPinWrite(GPIO_PORTF_BASE, GPIO_PIN_1, 0x00);
                  GPIOPinWrite(GPIO_PORTF_BASE, GPIO_PIN_3, 0x08);
                  GPIOPinWrite(GPIO_PORTF_BASE, GPIO_PIN_2, 0x04);
                  break;
              }
              case 7:
              {
                  GPIOPinWrite(GPIO_PORTF_BASE, GPIO_PIN_1, 0x00);
                  GPIOPinWrite(GPIO_PORTF_BASE, GPIO_PIN_3, 0x00);
                  GPIOPinWrite(GPIO_PORTF_BASE, GPIO_PIN_2, 0x00);
                  break;
              }
              default:
              {
                  GPIOPinWrite(GPIO_PORTF_BASE, GPIO_PIN_1, 0x02);
                  GPIOPinWrite(GPIO_PORTF_BASE, GPIO_PIN_3, 0x08);
                  GPIOPinWrite(GPIO_PORTF_BASE, GPIO_PIN_2, 0x04);
                  break;
              }
          }
     }
}
//void setup_GPIOs()
//{
//     delay_ms(2000);
//     GPIO_Clk_Enable(&GPIO_PORTF);
//     GPIO_Unlock(_GPIO_COMMIT_PIN_F0);
//     GPIO_Config(&GPIO_PORTF,
//                 (_GPIO_PINMASK_0 | _GPIO_PINMASK_4),
//                 _GPIO_DIR_INPUT,
//                 (_GPIO_CFG_PULL_UP | _GPIO_CFG_DIGITAL_ENABLE),
//                 _GPIO_PINCODE_NONE);
//     GPIO_Config(&GPIO_PORTF,
//                 (_GPIO_PINMASK_1 | _GPIO_PINMASK_2 | _GPIO_PINMASK_3),
//                 _GPIO_DIR_OUTPUT,
//                 (_GPIO_CFG_DIGITAL_ENABLE | _GPIO_CFG_DRIVE_8mA),
//                 _GPIO_PINCODE_NONE);
//}
